#!/bin/bash
# irssi-like irc client written in bash4.
# Copyright (C) 2011 Scott Nicholas <http://scottn.us>

: << EOF	# software license:
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
EOF

# config
bgcolor=4	#blue
nickname='mute-bash'
server='chat.us.freenode.net'
port=6667
channels=('#coredump')
fifo="fifo.$$"

# globals. no touch, k?
irc=
curnick=
curwin=0
edit_pos=0
tput_external=0
tput_internal=0
window=("status")
declare -A window_by_name=([status]=0) names_synced=()

#####################
### irc functions ###
#####################
irc_send() {
	printf '%s\r\n' "$1" >&"$irc"
}

irc_connect() {
	local host=$1 port=6667 chan

	[[ $2 ]] && port=$2
	exec {irc}<>"/dev/tcp/$host/$port" || exit
	irc_send "NICK $nickname"
	irc_send "USER $nickname user host :bash-irc user."
	for chan in "${channels[@]}"; do
		irc_send "JOIN $chan"
	done
}

irc_proc() {
	local nick user host src cmd dest params line=$1

	if [[ $line = :* ]]; then
		read -r src cmd dest params <<<"${line:1}"
		nick="${src%%!*}"
		user="${src#*!}"
		user="${user%%@*}"
		host="${src##*@}"
	else
		read -r cmd dest params <<<"$line"
	fi

	# :(
	[[ $dest = :* ]] && dest="${dest#?}"
	[[ $params = :* ]] && params="${params#?}"

	case "$cmd" in
		PING)		irc_send "PONG $dest";;
		PRIVMSG)	m_privmsg "$nick" "$user" "$host" "$dest" "$params";;
		NOTICE)		m_notice "$nick" "$user" "$host" "$dest" "$params";;
		001)		curnick=$dest;update_status_bar;;
		#useless noise
		002|003|004|005|251|252|253|254|255|265|266|250|375|372|376|332|333)
				;;	#do nothing
		353)		m_names "${params#* }";;	#names
		366)		m_366 "${params%% *}";;		#end of names
		MODE)		;;
		???)		write "$dest" "<<< [$cmd] $dest $params";;
		QUIT)		m_quit "$nick" "$user" "$host" "$dest $params";;
		JOIN)		m_join "$nick" "$user" "$host" "$dest";;
		PART)		m_part "$nick" "$user" "$host" "$dest";;
		NICK)		m_nick "$nick" "$user" "$host" "$dest";;
		*)		write "$dest" "<<< $line";;
	esac
}

# End of /NAMES
m_366() {
	local dest=$1

	[[ ${names_synced[$dest]} = 1 ]] && return
	names_synced[$dest]=1
	c_scan "$dest"
}

m_names() {
	local dest=${1%% *} nicks=${1#*:} win=cur

	[[ names_synced[$dest] = 1 ]] && return
	[[ ${window_by_name[$dest]} ]] && win=${window_by_name[$dest]}

	for nick in $nicks; do
		[[ $nick = [@+%\&]* ]] && nick=${nick#?}	#ops,etc?
		eval 'names_'$win'+=("$nick")'
	done
}

m_nick() {
	local nick=$1 user=$2 host=$3 newnick=$4

	if [[ $nick = $curnick ]]; then
		curnick=$newnick
		write cur "*** You are now known as $newnick"
	else
		write cur "*** $nick [$user@$host] is now known as $newnick"
	fi
}

m_join() {
	local nick=$1 user=$2 host=$3 dest=$4

	if [[ $nick = $curnick ]]; then
		window_create "$dest"
		window_select "${window_by_name[$dest]}"
	fi
	write "$dest" "*** $nick [$user@$host] has joined $dest"
}

m_part() {
	local nick=$1 user=$2 host=$3 dest=$4
	local next=

	if [[ $nick = $curnick ]]; then
		window_destroy "$dest"
	else
		write "$dest" "*** $nick [$user@$host] has left $dest"
	fi
}

m_quit() {
	local nick=$1 user=$2 host=$3 msg="${4% }"

	# fixme: need nickname list per channel, iterate, show in each chan
	write cur "*** $nick [$user@$host] has quit [$msg]"
}

m_notice() {
	local nick=$1 user=$2 host=$3 dest=$4 msg=$5

	write "$dest" "-$nick- $msg"
}

m_privmsg() {
	local nick=$1 user=$2 host=$3 dest=$4 msg=$5

	[[ $msg == * ]] && { m_ctcp "$nick" "$user" "$host" "$dest" "$msg"; return 0; }
	[[ $dest = $curnick ]] && dest=$nick
	write "$dest" "<$nick> $msg"
}

m_ctcp() {
	local nick=$1 user=$2 host=$3 dest=$4 msg

	msg="${5##}"
	msg="${msg%%}"
	read -r cmd msg <<< "$msg"

	[[ $dest = $curnick ]] && dest=$nick
	[[ $cmd = ACTION ]] || write "$dest" "*** $nick requests CTCP [$cmd] $msg"
	case "$cmd" in
		ACTION)		write "$dest" "* $nick $msg";;
		PING)		irc_send "NOTICE $1 :PING $msg";;
		VERSION)	irc_send "NOTICE $1 :VERSION bash-irc...!";;
	esac
}

########################
### window functions ###
########################
# major time saver
tput_init() {
	local c vt100_cup=$'\033''[6;6H' vt100_csr=$'\033''[6;6r'

	for c in civis clear cnorm el ind reset "setab $bgcolor" sgr0; do
		v=${c%% *}
		eval 'tput_'$v'=$(command tput $c && echo 'EOF')'
		eval 'tput_'$v'=${tput_'$v'%EOF}'
	done
	[[ $(tput cup 5 5) = $vt100_cup ]] && tput_internal_cup=1
	[[ $(tput csr 5 5) = $vt100_csr ]] && tput_internal_csr=1
}

tput() {
	case "$1" in
		civis|clear|cnorm|el|ind|reset|setab|sgr0)
			((tput_internal++))
			eval 'printf "%s" "$tput_'$1'"';;
		cup)
			if ((tput_internal_cup)); then
				((tput_internal++))
				printf '\033[%d;%dH' $(($2+1)) $(($3+1))
			else
				((tput_external++))
				command tput "$@"
			fi
			;;
		csr)
			if ((tput_internal_csr)); then
				((tput_internal++))
				printf '\033[%d;%dr' $(($2+1)) $(($3+1))
			else
				((tput_external++))
				command tput "$@"
			fi
			;;
		*)	((tput_external++)); command tput "$@";;
	esac
}

window_create() {
	local dest=$1 win

	window+=("$dest")
	names_synced[$dest]=0
	#now find it... o.O
	for win in "${!window[@]}"; do
		if [[ ${window[win]} = $dest ]]; then
			window_by_name[$dest]=$win
			break
		fi
	done
}

window_destroy() {
	local dest=$1 win=$1 i j

	c_window_next

	[[ $dest = [[:digit:]]* ]] || win=${window_by_name[$dest]}

	unset window_by_name[$dest]
	unset names_synced[$dest]

	#renumber all the indexs, ewww?
	for ((i = win, j = win + 1; i < ${#window[@]}; i++, j++)); do
#		[[ ${window[i]} ]] || ((j++))
		if [[ ${window[@]:j:1} ]]; then
			window[i]=${window[@]:j:1}
			eval 'buffer_'$i'=${buffer_'$j'[@]}'
			eval 'names_'$i'=${names_'$j'[@]}'
			window_by_name[${window[i]}]=$i
		else
			unset window[i]
			eval 'unset names_'$i
			eval 'unset buffer_'$i
		fi
	done
}

#omgomg
window_redraw() {
	local buf

	tput civis
	lines=$(tput lines)
	cols=$(tput cols)
	status=$((lines - 2))
	edit=$((lines - 1))
	curline=1
	tput sgr0
	tput clear
	tput csr 1 $((status-1))	# scroll area
	update_title_bar

	# redisplay buffer
	eval 'len=${#buffer_'$curwin'[@]}'
	((len>lines)) && len=$lines
	eval 'for buf in "${buffer_'$curwin'[@]:0-len}"; do
		write cur "$buf" n
	done'
	update_status_bar
	# always stay at edit line
	tput cup $edit 0
	tput el
	printf '[%s] %s' "${window[curwin]}" "$edit_line"
	tput cnorm
}

#fixme: erase using background color
update_title_bar() {
	tput cup 0 0
	tput setab $bgcolor
	printf '%*s' "-$cols" "debug stuff: term:${cols}x${lines} curline:$curline edit_pos:$edit_pos tput in:$tput_internal ext:$tput_external"
	tput sgr0
}

#fixme: erase using background color
update_status_bar() {
	local statusbar i=1

	tput cup $status 0
	tput setab $bgcolor

	statusbar="[$curnick]"
	for k in "${!window[@]}"; do
		statusbar+=" [$i:${window[k]}]"
		[[ $curwin = $k ]] && statusbar+='*'
		((i++))
	done
	printf '%*s' "-$cols" "$statusbar"
	tput sgr0
}

window_select() {
	curwin=$1
	window_redraw
}

# split in two functions... write_line/write_screen(less cups!)
write() {
	local dest=$1 line=$2 nobuffer=$3 win=$curwin k printed

	#improperly destined messages goto curwin
	[[ ${window_by_name[$dest]} ]] && win=${window_by_name[$dest]}
	[[ $nobuffer ]] || eval 'buffer_'$win'+=("$line")'

	# it's added to buffer now, if not on curwin, we're done.
	[[ $win = $curwin ]] || return

	#invisible cursor
	tput civis
	if ((curline==status)); then
		tput cup $((curline-1)) 0
		tput ind	#scroll
	else
		tput cup $((curline++)) 0
		tput el
	fi

	#wordwrap, kinda
	for ((printed=0; printed < (${#line}-cols); printed+=cols)); do
		printf '%s\n' "${line:printed:cols}"
		((curline++))
	done
	#but final line has no \n
	printf '%s' "${line:printed:cols}"

	update_title_bar
	update_status_bar
	#always go back to edit line
	tput cup $edit $((edit_pos + ${#window[curwin]} + 3))
	tput cnorm	#cursor visible
}

#######################
### input functions ###
#######################
input_cmd() {
	local cmd params

	read cmd params <<<"$1"

	case "$cmd" in
		exit)	exit;;
		quit)	irc_send "QUIT :$params"; sleep 1; exit;;
		join)	irc_send "JOIN :$params";;
		part)	irc_send "PART :$params";;
		nick)	irc_send "NICK :$params";;
		query)	c_query "$params";;
		quote)	irc_send "$params";;
		sc)	c_scan;;
		wins)	c_list_windows;;
		*)	write cur "*** Unknown command: $cmd";;
	esac
}

c_list_windows() {
	for win in "${!window[@]}"; do
		eval 'write cur "*** Window $win: ${window[win]} buf: ${#buffer_'$win'[@]}"'
	done
}

c_scan() {
	local nick i=0 line="  " dest=$1 win=$curwin

	[[ $dest ]] && win=${window_by_name[$dest]}
	write "${window[win]}" "[Users ${window[win]}]"
	eval 'for nick in "${names_'$win'[@]}"; do
		line+="[$nick] "
		if (((++i % 5) == 0)); then
			write "${window[win]}" "$line"
			line=
		fi
	done'

	((${#line} > 0)) && write "${window[win]}" "$line"
	eval 'write "${window[win]}" "${window[win]}: Total of ${#names_'$win'[@]} nicks"'
}

c_query() {
	local dest=$1

	window_create "$dest"
	window_select "${window_by_name[$dest]}"
}

c_window_next() {
	local k next
	for k in "${!window[@]}" "${!window[@]}"; do
		[[ $next = 1 ]] && {
			window_select "$k"
			break
		}
		[[ $curwin = $k ]] && next=1
	done
}

input_proc() {
	local ch="$1"

	case "$ch" in
	'C-?')	# backspace
		((edit_pos>0)) && ((edit_pos--))
		tput cup $edit $((edit_pos + ${#window[curwin]} + 3))
		tput el
		edit_line="${edit_line%?}"
		;;
	C-l)	window_redraw;;
	C-x)	c_window_next;;
	C-j)	# end of the line... soo much to do
		#erase edit box
		edit_pos=0
		tput cup $edit $((edit_pos + ${#window[curwin]} + 3))
		tput el

		if [[ $edit_line == /* ]]; then
			input_cmd "${edit_line:1}"
		else
			if [[ ${window[curwin]} = status ]]; then
				write status "echo: $edit_line"
			else
				write "${window[curwin]}" "<$curnick> $edit_line"
				irc_send "PRIVMSG ${window[curwin]} :$edit_line"
			fi
		fi
		edit_line=
		;;
	*)	# something normal?
		((edit_pos+=${#ch}))
		edit_line+=$ch
		#we should always have cursor at editbox...
		printf '%s' "$ch"
		;;
	esac
}

############
### main ###
############
exit_trap() {
	rm "$fifo"
	#buh bye kids
	reset
	echo "Thanks for trying..."
	kill -SIGTERM 0
}

declare -A key_bindings=(
	["C-["]="meta-"

	["meta-"]="meta-"

	["meta-O"]="meta2-"
	["meta-["]="meta2-"
	["meta2-"]="meta2-"

	#xterm mouse reporting
#	["meta2-M"]="mouse"

	["meta2-A"]="Up"
	["meta2-B"]="Down"
	["meta2-C"]="Right"
	["meta2-D"]="Left"
	["meta2-F"]="End"
	["meta2-H"]="Home"

	["meta2-1"]="meta2-1"	["meta2-1~"]="Home"
	["meta2-2"]="meta2-2"	["meta2-2~"]="Insert"
	["meta2-3"]="meta2-3"	["meta2-3~"]="Delete"
	["meta2-4"]="meta2-4"	["meta2-4~"]="End"
	["meta2-5"]="meta2-5"	["meta2-5~"]="PageUp"
	["meta2-6"]="meta2-6"	["meta2-6~"]="PageDown"

	#Xterm R6
	["meta2-P"]="F1"
	["meta2-Q"]="F2"
	["meta2-R"]="F3"
	["meta2-S"]="F4"

	#Linux
	["meta2-["]="meta2-["
	["meta2-[A"]="F1"
	["meta2-[B"]="F2"
	["meta2-[C"]="F3"
	["meta2-[D"]="F4"
	["meta2-[E"]="F5"

	#ESC[n~
	["meta2-1"]="meta2-1"
	["meta2-11"]="meta2-11"	["meta2-11~"]="F1"
	["meta2-12"]="meta2-12"	["meta2-12~"]="F2"
	["meta2-13"]="meta2-13"	["meta2-13~"]="F3"
	["meta2-14"]="meta2-14"	["meta2-14~"]="F4"
	["meta2-15"]="meta2-15"	["meta2-15~"]="F5"
	["meta2-17"]="meta2-17"	["meta2-17~"]="F6"
	["meta2-18"]="meta2-18"	["meta2-18~"]="F7"
	["meta2-19"]="meta2-19"	["meta2-19~"]="F8"
	["meta2-20"]="meta2-20"	["meta2-20~"]="F9"
	["meta2-21"]="meta2-21"	["meta2-21~"]="F10"
	["meta2-23"]="meta2-23"	["meta2-23~"]="F11"
	["meta2-24"]="meta2-24"	["meta2-24~"]="F12"

	#fun
	["w"]="w"
	["wt"]="wt"
	["wtf"]="what the FUCK!"

	[$'\001']="C-a"	[$'\002']="C-b"	[$'\003']="C-c"	[$'\004']="C-d"
	[$'\005']="C-e"	[$'\006']="C-f"	[$'\007']="C-g"	[$'\010']="C-h"
	[$'\011']="C-i"	[$'\012']="C-j"	[$'\013']="C-k"	[$'\014']="C-l"
	[$'\015']="C-m"	[$'\016']="C-n"	[$'\017']="C-o"	[$'\020']="C-p"
	[$'\021']="C-q"	[$'\022']="C-r"	[$'\023']="C-s"	[$'\024']="C-t"
	[$'\025']="C-u"	[$'\026']="C-v"	[$'\027']="C-w"	[$'\030']="C-x"
	[$'\031']="C-y"	[$'\032']="C-z"	[$'\033']='C-['	[$'\034']='C-\'
	[$'\035']='C-]'	[$'\036']='C-^'	[$'\037']='C-_'	[$'\177']='C-?'
)

handle_char() {
	local ch=$1 k l matches=0 cmd

	if [[ $ch ]]; then
		#pretreat...needed for control characters, because i'm dumb....?
		[[ ${key_bindings[$ch]} ]] && ch=${key_bindings[$ch]}
	else
		ch="C-@"	# NUL
	fi

	key_buf+=$ch
	[[ ${key_bindings[${key_buf}]} ]] && key_buf=${key_bindings[${key_buf}]}

	#this way we can handle time-out, i.e. just ESC
	if [[ ${key_bindings[${key_buf}]} ]] && IFS= read -rs -t 1 -N 1 ch; then
		handle_char "$ch"
	else
		case "$key_buf" in
			'meta2-M')	handle_mouse;;
			'meta-')	toggle_mouse;;
			*)		printf 'U%s\n' "${key_buf}";;
		esac
		unset key_buf
	fi
}

toggle_mouse() {
	local status

	((mouse_status = !mouse_status))
	if ((mouse_status == 1)); then
		printf '\e[?1000h'
		status='mouse enabled'
	else
		printf '\e[?1000l'
		status='mouse disabled'
	fi
	tput clear
	tput setab 4
	printf '%*s\n' "-$(tput cols)" "$status"
	tput sgr0
}

handle_mouse() {
	local button x y b enc

	IFS= read -rs -N 3 enc

	#convert char->dec
	printf -v button '%d' "'${enc:0:1}"
	printf -v y '%d' "'${enc:1:1}"
	printf -v x '%d' "'${enc:2:1}"

	#silly button bits
	((button&4)) && b+='shift+'
	((button&8)) && b+='meta+'
	((button&16)) && b+='ctrl+'
	case "$(( ((64 & button) >> 4) | (button & 3) ))" in
		0) b+='button1';;
		1) b+='button2';;
		2) b+='button3';;
		3) b+='release';;
		4) b+='wheel-up';;
		5) b+='wheel-down';;
	esac

	((x-=33,y-=33))
	printf '%15s (%d,%d)\n' "$b" "$x" "$y"
}

thread_user() {
	local ch

	while IFS= read -s -N 1 -r ch; do
		handle_char "$ch"
	done
} >&3

thread_server() {
	local line

	while IFS= read -u "$irc" -r line; do
		line="${line%$'\n'}"
		line="${line%$'\r'}"
		echo "S$line"
	done
} >&3

main() {
	local retval=0 line

	trap exit_trap EXIT
	trap window_redraw SIGWINCH

	mkfifo "$fifo" || {
		echo "Unable to create FIFO '$fifo'" >&2
		exit
	}
	# fd3=fifo, move stdin to fd4
	exec 3<>"$fifo" 4<&0 0<&-

	window_redraw
	thread_user <&4 &	#give stdin to user thread.

	write cur "*** Connecting to ${server}:${port}..."
	irc_connect "$server" "$port"
	write cur "*** Connected FD $irc"
	thread_server 4<&- &	#no stdin

	while IFS= read -r -u 3 line; do
		thread=${line:0:1}
		line=${line#?}
		case "$thread" in
			S) irc_proc "$line";;
			U) input_proc "$line";;
		esac
	done
}

tput_init
[[ $1 ]] && server=$1
[[ $2 ]] && port=$2
main
